## Question 1

In [9]:
M = int(input("Enter value M: "))
N = int(input("Enter value N: "))
A = int(input("Enter value A: "))
matA, matB, matC = [], [], []

##Inputs
print("First Array: ")
for i in range(M):
    temp = list(map(float, input().split()))   #Row-wise Input
    matA.append(temp)
print("Second Array: ")
for i in range(N):
    temp = list(map(float, input().split()))   #Row-wise Input
    matB.append(temp)

for i in range(M):
    temp = []
    for j in range(A):
        sum1 = 0.0
        for k in range(N):
            sum1 += matA[i][k] * matB[k][j]
        temp.append(float("{:.8f}".format(sum1)))
    matC.append(temp)

##Output
print("Dot Product of two arrays: ")
for res in matC:
    print(res)

Enter value M: 5
Enter value N: 3
Enter value A: 2
0.92825664 0.62790011 0.80130199
0.64283876 0.16558409 0.54573802
0.04319311 0.80229079 0.72512472
0.8005622 0.98844625 0.6982794
0.46600134 0.51451131 0.6415925
0.31898348 0.49050318
0.53845583 0.48259499
0.89102055 0.35539951
[1.34817155, 1.04311662]
[0.78047845, 0.58917953]
[1.09187707, 0.66607684]
[1.40978206, 1.11786567]
[0.99736045, 0.70489738]


## Question 2

In [14]:
print("Original Array: ", end = "")
lst = list(input().split())
digits, upper, lower = [], [], []
for i in lst:
    digits.append(True) if i.isdigit() else digits.append(False)
    upper.append(True) if i.isupper() else upper.append(False)
    lower.append(True) if i.islower() else lower.append(False)
print("Digits Only: ", digits)
print("Upper Only: ", upper)
print("Lower Only: ", lower)

Original Array: Python PHP JS Examples html 5
Digits Only:  [False, False, False, False, False, True]
Upper Only:  [False, True, True, False, False, False]
Lower Only:  [False, False, False, False, True, False]


## Question 3

In [44]:
X, Y = map(int, input().split())
lst1 = list(range(1, 16*X, X))
lst2 = list(range(1, 16*Y, Y))

import numpy as np

np1 = np.array(lst1)
np2 = np.array(lst2)

np1 = np1.reshape(4, 4)
np2 = np2.reshape(4, 4)

np3 = np.empty((4,4))

for i in range(4):
    for j in range(4):
        np3[i][j] = np1[i][j] - np2[i][j]

np3 = np.reshape(np3, 16)

print(np3.astype(int))

7 9
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


## Question 4

In [43]:
import numpy as np

P = np.array(list(map(int, input().split()))).reshape(3, 3)
Q = np.array(list(map(int, input().split()))).reshape(3, 3)

res = np.empty((3, 3))

for i in range(3):
    for j in range(3):
        res[i][j] = P[i][j] - Q[i][j]
print(res.astype(int))

23 56 87 3 6 96 4 6 78
12 34 54 7 2 54 6 2 78
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
